#
# Authors: zhengyu li <zhengyu_li@gmail.com>
#

MESSAGE (STATUS "Using bundled find jansson")

FIND_PATH (
  LIBJANSSON_INCLUDE_DIR
  NAMES jansson.h
  PATHS /usr/include /usr/local/include/)

FIND_LIBRARY (
  LIBJANSSON_LIBRARY
  NAMES jansson
  PATHS /usr/lib/ /usr/local/lib/ /usr/lib64/ /usr/lcocal/lib64/)

IF (LIBJANSSON_INCLUDE_DIR AND LIBJANSSON_LIBRARY)
  SET (JANSSON_FOUND 1)
  INCLUDE_DIRECTORIES (${LIBJANSSON_INCLUDE_DIR})
ELSE (LIBJANSSON_INCLUDE_DIR AND LIBJANSSON_LIBRARY)
  SET (JANSSON_FOUND 0)
ENDIF (LIBJANSSON_INCLUDE_DIR AND LIBJANSSON_LIBRARY)

MARK_AS_ADVANCED (
  LIBJANSSON_INCLUDE_DIR
  LIBJANSSON_LIBRARY)
