#
# Authors: zhengyu li <zhengyu_li@gmail.com>
#

MESSAGE (STATUS "Using bundled find hiredis")

FIND_PATH (
  LIBHIREDIS_INCLUDE_DIR
  NAMES hiredis.h
  PATHS /usr/include/hiredis/ /usr/local/include/hiredis/)

FIND_LIBRARY (
  LIBHIREDIS_LIBRARY
  NAMES hiredis
  PATHS /usr/lib/ /usr/local/lib/ /usr/lib64/ /usr/lcocal/lib64/)

IF (LIBHIREDIS_INCLUDE_DIR AND LIBHIREDIS_LIBRARY)
  SET (HIREDIS_FOUND 1)
  INCLUDE_DIRECTORIES (${LIBHIREDIS_INCLUDE_DIR})
ELSE (LIBHIREDIS_INCLUDE_DIR AND LIBHIREDIS_LIBRARY)
  SET (HIREDIS_FOUND 0)
ENDIF (LIBHIREDIS_INCLUDE_DIR AND LIBHIREDIS_LIBRARY)

MARK_AS_ADVANCED (
  LIBHIREDIS_INCLUDE_DIR
  LIBHIREDIS_LIBRARY)
