#
# Authors: zhengyu li <zhengyu_li@gmail.com>
#

MESSAGE (STATUS "Using bundled find ini_config")

FIND_PATH (
  LIBINICONFIG_INCLUDE_DIR
  NAMES ini_config.h
  PATHS /usr/include /usr/local/include/)

FIND_LIBRARY (
  LIBINICONFIG_LIBRARY
  NAMES ini_config
  PATHS /usr/lib/ /usr/local/lib/ /usr/lib64/ /usr/lcocal/lib64/)

IF (LIBINICONFIG_INCLUDE_DIR AND LIBINICONFIG_LIBRARY)
  SET (INICONFIG_FOUND 1)
  INCLUDE_DIRECTORIES (${LIBINICONFIG_INCLUDE_DIR})
ELSE (LIBINICONFIG_INCLUDE_DIR AND LIBINICONFIG_LIBRARY)
  SET (INICONFIG_FOUND 0)
ENDIF (LIBINICONFIG_INCLUDE_DIR AND LIBINICONFIG_LIBRARY)

MARK_AS_ADVANCED (
  LIBINICONFIG_INCLUDE_DIR
  LIBINICONFIG_LIBRARY)
